<a href="https://colab.research.google.com/github/FelixEbenezer/Deep-Learning-TensorFlow-Hub/blob/main/TensorFlow_Hub_Classifica%C3%A7%C3%A3o_de_textos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow Hub - Classificação de textos

- Baseado em: https://www.tensorflow.org/hub/tutorials/tf2_text_classification?hl=pt-br

# Importação das bibliotecas

In [ ]:
import numpy as np
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_datasets as tfds
import matplotlib.pyplot as plt
print('Versão do TensorFlow: ', tf.__version__)
print('Versão do TensorFlow Hub: ', hub.__version__)

Versão do TensorFlow:  2.8.2
Versão do TensorFlow Hub:  0.12.0


# Base de dados

- Extraído do site imdb: 0 - negativo, 1 - positivo

In [ ]:
dados_treinamento, dados_teste = tfds.load(name = 'imdb_reviews', split = ['train', 'test'], batch_size = -1, as_supervised=True)
X_treinamento, y_treinamento = tfds.as_numpy(dados_treinamento)
X_teste, y_teste = tfds.as_numpy(dados_teste)

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

0 examples [00:00, ? examples/s]

Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incomplete9Z6NP3/imdb_reviews-train.tfrecord


  0%|          | 0/25000 [00:00<?, ? examples/s]

0 examples [00:00, ? examples/s]

Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incomplete9Z6NP3/imdb_reviews-test.tfrecord


  0%|          | 0/25000 [00:00<?, ? examples/s]

0 examples [00:00, ? examples/s]

Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incomplete9Z6NP3/imdb_reviews-unsupervised.tfrecord


  0%|          | 0/50000 [00:00<?, ? examples/s]

Dataset imdb_reviews downloaded and prepared to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0. Subsequent calls will reuse this data.
Instructions for updating:
Use `tf.data.Dataset.get_single_element()`.


Instructions for updating:
Use `tf.data.Dataset.get_single_element()`.


In [ ]:
X_treinamento.shape, y_treinamento.shape

((25000,), (25000,))

In [ ]:
X_teste.shape, y_teste.shape

((25000,), (25000,))

In [ ]:
X_treinamento[0:2]

array([b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.",
       b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on the sette and having just eaten a lot. However on this occasion I fell asleep because the film was rubbish. The plot 

In [ ]:
y_treinamento[0:2]

array([0, 0])

In [ ]:
X_teste[0:2]

array([b"There are films that make careers. For George Romero, it was NIGHT OF THE LIVING DEAD; for Kevin Smith, CLERKS; for Robert Rodriguez, EL MARIACHI. Add to that list Onur Tukel's absolutely amazing DING-A-LING-LESS. Flawless film-making, and as assured and as professional as any of the aforementioned movies. I haven't laughed this hard since I saw THE FULL MONTY. (And, even then, I don't think I laughed quite this hard... So to speak.) Tukel's talent is considerable: DING-A-LING-LESS is so chock full of double entendres that one would have to sit down with a copy of this script and do a line-by-line examination of it to fully appreciate the, uh, breadth and width of it. Every shot is beautifully composed (a clear sign of a sure-handed director), and the performances all around are solid (there's none of the over-the-top scenery chewing one might've expected from a film like this). DING-A-LING-LESS is a film whose time has come.",
       b"A blackly comic tale of a down-trodden p

In [ ]:
y_teste[0:2]

array([1, 1])

In [ ]:
np.unique(y_treinamento, return_counts=True)

(array([0, 1]), array([12500, 12500]))

In [ ]:
np.unique(y_teste, return_counts=True)

(array([0, 1]), array([12500, 12500]))

# Construção e treinamento da rede neural

In [ ]:
# Mais modelos: https://tfhub.dev/s?module-type=text-embedding
caminho_modelo = 'https://tfhub.dev/google/nnlm-en-dim50/2'

In [ ]:
camada_embedding = hub.KerasLayer(caminho_modelo, input_shape = [], dtype = tf.string, trainable=True)

In [ ]:
# Word embedding: https://iaexpert.academy/2019/04/12/word-embedding-transformando-palavras-em-numeros/
camada_embedding(X_treinamento[0:2])

<tf.Tensor: shape=(2, 50), dtype=float32, numpy=
array([[ 0.5423194 , -0.01190171,  0.06337537,  0.0686297 , -0.16776839,
        -0.10581177,  0.168653  , -0.04998823, -0.31148052,  0.07910344,
         0.15442258,  0.01488661,  0.03930155,  0.19772716, -0.12215477,
        -0.04120982, -0.27041087, -0.21922147,  0.26517656, -0.80739075,
         0.25833526, -0.31004202,  0.2868321 ,  0.19433866, -0.29036498,
         0.0386285 , -0.78444123, -0.04793238,  0.41102988, -0.36388886,
        -0.58034706,  0.30269453,  0.36308962, -0.15227163, -0.4439151 ,
         0.19462997,  0.19528405,  0.05666233,  0.2890704 , -0.28468323,
        -0.00531206,  0.0571938 , -0.3201319 , -0.04418665, -0.08550781,
        -0.55847436, -0.2333639 , -0.20782956, -0.03543065, -0.17533456],
       [ 0.56338924, -0.12339553, -0.10862677,  0.7753425 , -0.07667087,
        -0.15752274,  0.01872334, -0.08169781, -0.3521876 ,  0.46373403,
        -0.08492758,  0.07166861, -0.00670818,  0.12686071, -0.19326551,
 

In [ ]:
modelo = tf.keras.Sequential()
modelo.add(camada_embedding)
# 50 -> 16 -> 1
modelo.add(tf.keras.layers.Dense(16, activation = 'relu'))
modelo.add(tf.keras.layers.Dense(1))
modelo.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 keras_layer (KerasLayer)    (None, 50)                48190600  
                                                                 
 dense (Dense)               (None, 16)                816       
                                                                 
 dense_1 (Dense)             (None, 1)                 17        
                                                                 
Total params: 48,191,433
Trainable params: 48,191,433
Non-trainable params: 0
_________________________________________________________________


In [ ]:
modelo.compile(optimizer = 'adam', loss = tf.losses.BinaryCrossentropy(from_logits=True), metrics = ['accuracy'])

In [ ]:
modelo.fit(X_treinamento, y_treinamento, epochs = 20, batch_size = 512, verbose = 1)

Epoch 1/20
49/49 [==============================] - 6s 40ms/step - loss: 0.6238 - accuracy: 0.5706
Epoch 2/20
49/49 [==============================] - 2s 38ms/step - loss: 0.4289 - accuracy: 0.7983
Epoch 3/20
49/49 [==============================] - 2s 39ms/step - loss: 0.2887 - accuracy: 0.8814
Epoch 4/20
49/49 [==============================] - 2s 38ms/step - loss: 0.2098 - accuracy: 0.9210
Epoch 5/20
49/49 [==============================] - 2s 38ms/step - loss: 0.1534 - accuracy: 0.9470
Epoch 6/20
49/49 [==============================] - 2s 39ms/step - loss: 0.1125 - accuracy: 0.9645
Epoch 7/20
49/49 [==============================] - 2s 39ms/step - loss: 0.0802 - accuracy: 0.9776
Epoch 8/20
49/49 [==============================] - 2s 39ms/step - loss: 0.0557 - accuracy: 0.9869
Epoch 9/20
49/49 [==============================] - 2s 38ms/step - loss: 0.0384 - accuracy: 0.9933
Epoch 10/20
49/49 [==============================] - 2s 38ms/step - loss: 0.0265 - accuracy: 0.9966
Epoch 11/

In [ ]:
resultados = modelo.evaluate(X_teste, y_teste)
print(resultados)

782/782 [==============================] - 4s 5ms/step - loss: 0.5842 - accuracy: 0.8496
[0.5842357277870178, 0.8496400117874146]


# Previsões com textos

In [ ]:
X_teste[0:5]

array([b"There are films that make careers. For George Romero, it was NIGHT OF THE LIVING DEAD; for Kevin Smith, CLERKS; for Robert Rodriguez, EL MARIACHI. Add to that list Onur Tukel's absolutely amazing DING-A-LING-LESS. Flawless film-making, and as assured and as professional as any of the aforementioned movies. I haven't laughed this hard since I saw THE FULL MONTY. (And, even then, I don't think I laughed quite this hard... So to speak.) Tukel's talent is considerable: DING-A-LING-LESS is so chock full of double entendres that one would have to sit down with a copy of this script and do a line-by-line examination of it to fully appreciate the, uh, breadth and width of it. Every shot is beautifully composed (a clear sign of a sure-handed director), and the performances all around are solid (there's none of the over-the-top scenery chewing one might've expected from a film like this). DING-A-LING-LESS is a film whose time has come.",
       b"A blackly comic tale of a down-trodden p

In [ ]:
y_teste[0:5]

array([1, 1, 0, 0, 1])

In [ ]:
previsoes = modelo.predict(X_teste[0:5])

In [ ]:
previsoes

array([[  2.6337864],
       [  2.485549 ],
       [ -3.4984972],
       [-10.75816  ],
       [  9.393039 ]], dtype=float32)

In [ ]:
previsoes = tf.nn.sigmoid(previsoes).numpy()
previsoes

array([[9.330046e-01],
       [9.231225e-01],
       [2.935502e-02],
       [2.127068e-05],
       [9.999167e-01]], dtype=float32)

In [ ]:
y_teste[0:5]

array([1, 1, 0, 0, 1])

In [ ]:
previsoes = (previsoes >= 0.5)
previsoes

array([[ True],
       [ True],
       [False],
       [False],
       [ True]])